version: "3"

services:
# https://hub.docker.com/r/nclcloudcomputing/javabenchmarkapp
  javabenchmarkapp:
    image: "nclcloudcomputing/javabenchmarkapp"
    deploy:
      replicas: 1
    ports:
      - "8080:8080"

# https://hub.docker.com/r/locustio/locust
  locust_master:
    image: "locustio/locust"
    deploy:
      replicas: 1
    ports:
      - "8089:8089"
    volumes:
      - "./:/mnt/locust"
    command: "-f /mnt/locust/locustfile.py --master -H http://master:8089"

  locust_worker:
    image: "locustio/locust"
    deploy:
      replicas: 1
    volumes:
      - "./:/mnt/locust"
    command: "-f /mnt/locust/locustfile.py --worker --master-host master"

# https://hub.docker.com/r/google/cadvisor
  cadvisor:
    image: "gcr.io/cadvisor/cadvisor:v0.45.0"
    deploy:
      replicas: 1
    ports:
      - "8081:8080"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/dev/disk/:/dev/disk:ro"

# https://hub.docker.com/r/dockersamples/visualizer
  visualizer:
    image: "dockersamples/visualizer"
    deploy:
      replicas: 1
    ports:
      - "8082:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  # https://hub.docker.com/_/mongo
  mongo:
    image: "mongo"
    deploy:
      replicas: 1
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=db

# https://hub.docker.com/_/mongo-express/
  mongo-express:
    image: "mongo-express"
    depends_on:
      - "mongodb"
    deploy:
      replicas: 1
    ports:
      - "8083:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_POR=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
